export const GARDEN_CONCEPTS: Record<string, string[]> = {
  trust: ["trust", "depend", "faith", "rely", "uncertain", "uncertainty", "confidence"],
  grace: ["grace", "mercy", "gift", "forgive", "forgiveness", "freedom", "undeserved"],
  identity: ["identity", "called", "chosen", "belong", "child", "name", "adopted"],
  rest: ["rest", "peace", "still", "sabbath", "burden", "weary", "quiet"],
  obedience: ["obey", "obedience", "practice", "respond", "follow", "action", "submit"],
  prayer: ["pray", "prayer", "ask", "cry", "thank", "worship", "intercede"],
  wisdom: ["wisdom", "understand", "discern", "listen", "learn", "know", "instruction"],
  justice: ["justice", "righteous", "righteousness", "fair", "oppress", "oppressed", "judge"],
  suffering: ["suffer", "suffering", "pain", "trial", "trials", "affliction", "grief"],
  covenant: ["covenant", "promise", "promises", "faithful", "faithfulness", "oath"],
  creation: ["create", "created", "creation", "maker", "formed", "earth", "heavens"],
  repentance: ["repent", "repentance", "turn", "return", "confess", "confession"],
  hope: ["hope", "expect", "expectation", "wait", "waiting", "future", "promise"],
  love: ["love", "beloved", "compassion", "kindness", "neighbor", "charity"],
  fear: ["fear", "afraid", "anxious", "anxiety", "worry", "courage", "comfort"],
  salvation: ["save", "saved", "salvation", "rescue", "redeem", "redeemed", "deliver"],
  holiness: ["holy", "holiness", "pure", "purity", "sanctify", "set apart"],
  community: ["community", "church", "body", "together", "fellowship", "brother", "sister"],
  leadership: ["lead", "leader", "shepherd", "serve", "authority", "guide", "pastor"],
  temptation: ["tempt", "temptation", "desire", "resist", "test", "escape"],
  patience: ["patience", "patient", "endure", "endurance", "persevere", "slow"],
};
