import { useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { colors } from '@/lib/theme';

const notes=[{id:'genesis-1-2',reference:'Genesis 1:2',tag:'Sovereignty',title:'Life moving over chaos',body:'“Spirit of God” (Ruach) signifies dynamic life moving over chaos.',time:'Today'},{id:'john-1-1',reference:'John 1:1',tag:'Covenants',title:'A cosmic echo',body:'The connection to Genesis is a cosmic echo. Logos equals structural order.',time:'Yesterday'}];
const filters=['All','Sovereignty','Covenants'];
export default function Garden(){const router=useRouter();const [filter,setFilter]=useState('All');const visible=useMemo(()=>filter==='All'?notes:notes.filter(n=>n.tag===filter),[filter]);return <Screen title="Garden"><View style={s.summary}><View><Text style={s.summaryLabel}>YOUR GARDEN</Text><Text style={s.summaryValue}>2 reflections</Text></View><Pressable accessibilityRole="button" onPress={()=>router.push('/note/new')} style={s.newButton}><Ionicons name="add" size={20} color="#081712"/><Text style={s.newText}>New note</Text></Pressable></View><View style={s.filters}>{filters.map(item=><Pressable key={item} onPress={()=>setFilter(item)} style={[s.filter,filter===item&&s.filterActive]}><Text style={[s.filterText,filter===item&&s.filterTextActive]}>{item}</Text></Pressable>)}</View><FlatList data={visible} keyExtractor={x=>x.id} showsVerticalScrollIndicator={false} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>No reflections here yet.</Text>} renderItem={({item})=><Pressable onPress={()=>router.push({pathname:'/note/[id]',params:{id:item.id}})} style={({pressed})=>[s.card,pressed&&s.pressed]}><View style={s.metaRow}><Text style={s.reference}>{item.reference}</Text><Text style={s.time}>{item.time}</Text></View><Text style={s.title}>{item.title}</Text><Text numberOfLines={2} style={s.body}>{item.body}</Text><View style={s.cardBottom}><Text style={s.tag}>#{item.tag}</Text><Ionicons name="chevron-forward" size={17} color={colors.muted}/></View></Pressable>}/></Screen>}
const s=StyleSheet.create({summary:{margin:18,marginBottom:12,padding:16,borderRadius:16,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderWidth:1,borderColor:colors.line},summaryLabel:{color:colors.muted,fontSize:9,fontWeight:'700',letterSpacing:1.3},summaryValue:{color:colors.text,fontSize:18,fontWeight:'700',marginTop:4},newButton:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:colors.green,paddingHorizontal:13,paddingVertical:10,borderRadius:11},newText:{color:'#081712',fontWeight:'800',fontSize:12},filters:{flexDirection:'row',gap:7,paddingHorizontal:18,marginBottom:12},filter:{paddingHorizontal:13,paddingVertical:8,borderRadius:18,backgroundColor:colors.surface},filterActive:{backgroundColor:colors.green},filterText:{color:colors.muted,fontSize:12},filterTextActive:{color:'#081712',fontWeight:'700'},list:{paddingHorizontal:18,paddingBottom:28},card:{backgroundColor:colors.surface,padding:16,borderRadius:15,borderWidth:1,borderColor:colors.line,marginBottom:11},pressed:{opacity:.7},metaRow:{flexDirection:'row',justifyContent:'space-between'},reference:{color:colors.green,fontSize:11,fontWeight:'700'},time:{color:colors.muted,fontSize:10},title:{color:colors.text,fontSize:17,fontWeight:'700',marginTop:10},body:{color:colors.muted,lineHeight:19,marginTop:6},cardBottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:13},tag:{color:colors.gold,fontSize:11},empty:{color:colors.muted,textAlign:'center',padding:28}});
