import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { colors } from '@/lib/theme';
import { useAppSettings } from '@/state/AppSettings';

const verses=['In the beginning God created the heavens and the earth.','Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.','And God said, “Let there be light,” and there was light.','God saw that the light was good, and He separated the light from the darkness.','God called the light “day,” and the darkness He called “night.” And there was evening, and there was morning—the first day.'];
export default function Read(){const router=useRouter();const {darkMode,showVerseNumbers}=useAppSettings();return <Screen title="Read"><View style={s.location}><Pressable style={s.locationButton}><View><Text style={s.book}>Genesis</Text><Text style={s.chapter}>Chapter 1</Text></View><Ionicons name="chevron-down" size={18} color={colors.muted}/></Pressable><Pressable style={s.translation}><Text style={s.translationText}>BSB</Text></Pressable><Pressable accessibilityLabel="Reading options" style={s.iconButton}><Ionicons name="text-outline" size={20} color={colors.muted}/></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.body}><Text style={s.section}>THE BEGINNING</Text>{verses.map((verse,index)=><Text key={verse} style={[s.verse,{color:darkMode?'#e2e8e6':'#273d36'}]}>{showVerseNumbers&&<Text style={s.num}>{index+1}  </Text>}{verse}</Text>)}<View style={s.insight}><View style={s.insightTop}><View><Text style={s.insightLabel}>YOUR REFLECTION</Text><Text style={s.insightAnchor}>Genesis 1:2</Text></View><Pressable onPress={()=>router.push('/note/new')} style={s.edit}><Ionicons name="create-outline" size={18} color={colors.green}/></Pressable></View><Text style={s.insightText}>“Spirit of God” (Ruach) signifies dynamic life moving over chaos.</Text><Pressable onPress={()=>router.push({pathname:'/note/[id]',params:{id:'genesis-1-2'}})}><Text style={s.open}>Open in Garden →</Text></Pressable></View></ScrollView></Screen>}
const s=StyleSheet.create({location:{height:64,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,borderColor:colors.line},locationButton:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},book:{color:colors.text,fontSize:16,fontWeight:'700'},chapter:{color:colors.muted,fontSize:10,marginTop:2},translation:{paddingHorizontal:11,paddingVertical:8,borderRadius:9,backgroundColor:colors.surface},translationText:{color:colors.gold,fontSize:11,fontWeight:'700'},iconButton:{width:36,height:36,borderRadius:9,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},body:{padding:22,paddingBottom:32},section:{color:colors.muted,fontSize:10,fontWeight:'700',letterSpacing:1.5,marginBottom:20},verse:{fontFamily:'serif',fontSize:19,lineHeight:32,marginBottom:17},num:{color:colors.gold,fontSize:11,fontWeight:'700'},insight:{marginTop:8,backgroundColor:colors.surface,borderRadius:16,padding:16,borderWidth:1,borderColor:colors.line},insightTop:{flexDirection:'row',justifyContent:'space-between'},insightLabel:{color:colors.green,fontSize:9,fontWeight:'700',letterSpacing:1.3},insightAnchor:{color:colors.muted,fontSize:10,marginTop:3},edit:{width:34,height:34,alignItems:'center',justifyContent:'center'},insightText:{color:colors.text,lineHeight:20,marginTop:12},open:{color:colors.gold,fontSize:11,fontWeight:'700',marginTop:14}});
