import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { colors } from '@/lib/theme';
import { useAppSettings } from '@/state/AppSettings';

function Setting({name,icon,value,onChange,detail,onPress,last}:{name:string;icon:any;value?:boolean;onChange?:(v:boolean)=>void;detail?:string;onPress?:()=>void;last?:boolean}){const content=<><Ionicons name={icon} size={18} color={colors.muted}/><Text style={s.name}>{name}</Text>{onChange?<Switch value={value} onValueChange={onChange} trackColor={{false:'#52645e',true:colors.green}} thumbColor="#eef3f0"/>:<><Text style={s.detail}>{detail}</Text>{onPress&&<Ionicons name="chevron-forward" size={17} color={colors.muted}/>}</>}</>;return onPress?<Pressable onPress={onPress} style={[s.row,last&&s.last]}>{content}</Pressable>:<View style={[s.row,last&&s.last]}>{content}</View>}
export default function Settings(){const router=useRouter();const {darkMode,setDarkMode,redLettering,setRedLettering,showVerseNumbers,setShowVerseNumbers,reminderHour,reminderMinute,reminderPeriod}=useAppSettings();const [biometric,setBiometric]=useState(false);return <Screen title="Settings"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.body}><Text style={s.label}>ACCOUNT</Text><View style={s.group}><Setting icon="star-outline" name="Subscription" detail="Free" onPress={()=>router.push('/subscription')} last/></View><Text style={s.label}>APPEARANCE</Text><View style={s.group}><Setting icon="moon-outline" name="Dark Mode" value={darkMode} onChange={setDarkMode}/><Setting icon="color-palette-outline" name="Reading Theme" detail={darkMode?'Selah Dark':'Parchment'} onPress={()=>router.push('/preferences')} last/></View><Text style={s.label}>READER SETTINGS</Text><View style={s.group}><Setting icon="chatbox-ellipses-outline" name="Red Lettering" value={redLettering} onChange={setRedLettering}/><Setting icon="list-outline" name="Show Verse Numbers" value={showVerseNumbers} onChange={setShowVerseNumbers} last/></View><Text style={s.label}>PRIVACY & SECURITY</Text><View style={s.group}><Setting icon="finger-print-outline" name="Biometric Lock" value={biometric} onChange={setBiometric}/><Setting icon="notifications-outline" name="Daily Reminders" detail={`${reminderHour}:${reminderMinute} ${reminderPeriod}`} onPress={()=>router.push('/reminders')} last/></View><Pressable onPress={()=>router.replace('/login')} style={s.logout}><Text style={s.logoutText}>Sign Out</Text></Pressable></ScrollView></Screen>}
const s=StyleSheet.create({body:{padding:18,paddingBottom:30},label:{color:colors.muted,fontSize:10,fontWeight:'700',letterSpacing:1.3,marginTop:4,marginBottom:7},group:{backgroundColor:colors.surface,borderRadius:14,borderWidth:1,borderColor:colors.line,overflow:'hidden',marginBottom:16},row:{minHeight:54,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderColor:colors.line},last:{borderBottomWidth:0},name:{color:colors.text,fontWeight:'600',flex:1},detail:{color:colors.green,fontSize:12},logout:{height:48,borderRadius:12,borderWidth:1,borderColor:'rgba(234,133,133,.2)',backgroundColor:'rgba(234,133,133,.05)',alignItems:'center',justifyContent:'center',marginTop:5},logoutText:{color:colors.danger,fontWeight:'700'}});
